# Hyprland plugins config
# Install plugins first:
#   hyprpm update
#   hyprpm add https://github.com/sandwichfarm/hyprexpo
#   hyprpm enable hyprexpo
#   hyprpm reload

plugin {
    hyprexpo {
        columns = 3
        gaps_in = 5
        gaps_out = 20
        bg_col = rgb(111111)
        workspace_method = center current
        gesture_distance = 300

        label_enable = 0
    }
}
